### ISSUE TITLE
Couldn't update a forked gist

### ISSUE THREAD

**Issue by tyru** [lambdalisue/vim-gista#73]
After I applied #71 

I couldn't update a forked gist.

1. `:Gista fork ...`
1. `:Gista list` and open the forked gist
1. `:w`

causes:

```
vim-gista: A remote content of a gist 18b30b3874522fc16595 in GitHub is modified from last access.
Use ":w!" to post changes to GitHub forcedly or :Gista post to create a new Gist
```

**Comment by lambdalisue** [comment]
As the message said, you need to use `:w!` for instance.

Gist API returns GUID to determine if the gist is updated or not for all API. 
vim-gista use that GUID to check if a remote gist is updated or not **to reduce API use** (to prevent API limit).
However a GUID returned from any POST action (e.g. `:Gista post` or `:Gista fork`) will be differ from next GET request and that's why vim-gista assume that the remote content is modified.

If I perform GET request after POST, it can be fixed but while requesting HTTP access is time-consuming, I decided to leave this while user easily update the remote content with `:w!`.

**Comment by tyru** [comment]
OK, now I understand this is expected behavior.
Please feel free to ignore, too :) #72

**Comment by lambdalisue** [comment]
Thanks for understanding ;-)
